
#  切换使用哪个编译器

SET=xinjiang
SET=pc
SET=hisi

ifeq ($(SET), xinjiang)
TAIL=arm
CC=/work/toolchain_R2_EABI/usr/bin/arm-none-linux-gnueabi-gcc
else ifeq ($(SET), hisi)
TAIL=
CC=arm-hisiv100nptl-linux-gcc
else ifeq ($(SET), pc)
TAIL=x86
CC=gcc
else 
TAIL=x86
CC=gcc
endif


