all:
	@cd ./utils/;   make
	@cd ./corelib/;   make
	@cd ./mod_led/;   make
	@cd ./mod_scan/;  make
	@cd ./mod_scan_tty/;  make

clean:
	@cd ./utils/;   make clean
	@cd ./corelib/;   make clean
	@cd ./mod_led/;   make clean
	@cd ./mod_scan/;  make clean
	@cd ./mod_scan_tty/;  make clean
